# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # Prevents simultaneous deployments
    steps:
      - uses: actions/checkout@v4

      # Setup PHP to run composer install (Optimize deployment)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Adjust to your PHP version

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      # Install Flyctl (Fly.io CLI)
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # Execute Deployment
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}